Wolo 286 reserve list
yarpo/wolo-app pull request #133
Opened 2024-06-01 13:15 UTC by ayakiri

Jira: https://woloapp.atlassian.net/browse/WOLO-286

- joiniing reserve (event http://localhost:3000/details/14 is easy to fill)
- leaving reserve

2024-06-02 11:50 UTC, KinWaj commented on src/Views/Details/ShiftCard/ShiftCard.js
> +    const isSignedIn = userShifts.map(shift => shift.shiftId).includes(shiftId);
![image](https://github.com/yarpo/wolo-app/assets/99564630/acbca226-16c3-416a-8c06-6f276ea32599)
I don't know what's going on but I can't launch any event due to that
Did even `npm install`, didn't work, I can't see this issue when I'm not logged in, something to do with logged in users?

2024-06-02 12:17 UTC, KinWaj reviewed
As admin, I cannot look at the event. It gives me errors.
![image](https://github.com/yarpo/wolo-app/assets/99564630/159d144c-babd-4d01-854e-ea8f5d5726d3)

2024-06-02 12:56 UTC, KinWaj requested changes
need fix for admin, other than that works

2024-06-03 18:02 UTC, kamil-kaczor approved these changes

2024-06-04 10:18 UTC, KinWaj approved these changes
works

2024-06-04 10:18 UTC, merged