Tests and translation
yarpo/wolo-app pull request #43
Opened 2023-12-09 12:11 UTC by Filiposki54

added translations and tests to the login and registration form

2023-12-10 18:24 UTC, KinWaj commented on public/locales/en/translation.json
> +  "showPassword": "Show Password:",
why is there ':' and in ukrainian and russian translations doesn't have it ?

2023-12-10 18:24 UTC, KinWaj commented on public/locales/pl/translation.json
> +  "showPassword": "Pokaż hasło:",
same here

2023-12-10 18:40 UTC, KinWaj requested changes
small changes required

2023-12-10 18:40 UTC, KinWaj commented on src/Components/Signup/Signup.js
> +              <p>{t('orContinueWith')}</p>
should be something different like 'or', got Agata's permission with that :) 
needed new variable with 'or ' in other lang's

2023-12-12 18:15 UTC, ayakiri approved these changes
Fixed Kinga's notes, looks good to me

2023-12-12 18:42 UTC, merged